### ISSUE TITLE
Add BODICEA output

### ISSUE THREAD

**Issue by Chen2x** [GA4GH-Pedigree-Standard/pedigree-tools#10]

**Comment by alextsaihi** [comment]
Hi @buske, I tried contacting you over Slack earlier this week about this feature. I have currently written the part to format the output into a BOADICEA string, but haven't tested it out yet. 

When I tried following the steps on the README from the main branch to run pedigree-tools as its source code, I receive an error that says the yargs package is missing. 
I manually install yargs into the nodejs subfolder and I'm receiving this error:

```
% pedigree-tools import --from ped --file examples/simple.ped > test.json
/Users/atsai/Desktop/pedigree-test/pedigree-tools/nodejs/src/ontology.js:71
			throw new Error(
			^

Error: KIN:047 not found in the concept object.
Please update the concept object.
    at /Users/atsai/Desktop/pedigree-test/pedigree-tools/nodejs/src/ontology.js:71:10
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/atsai/Desktop/pedigree-test/pedigree-tools/nodejs/src/ontology.js:65:7)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Module._load (node:internal/modules/cjs/loader:827:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/atsai/Desktop/pedigree-test/pedigree-tools/nodejs/src/model.js:12:18)

Node.js v18.3.0
```

**Comment by buske** [comment]
Hi @alextsaihi, it looks like the new terms recently added to the terminology haven't yet been added to the ontology.js file CODE_TO_CONCEPT map. Will reply to your other point via Slack now.

**Comment by samuellawty** [comment]
> Hi @alextsaihi, it looks like the new terms recently added to the terminology haven't yet been added to the ontology.js file CODE_TO_CONCEPT map. Will reply to your other point via Slack now.

Hi @buske I also encountered this question, could you tell me to how to edit the `ontology.js` file to make the program work here?

**Comment by samuellawty** [comment]
Ok, I think I have solved the problem. I edit the `ontology.js` file by adding missing terms in https://github.com/GA4GH-Pedigree-Standard/family_history_terminology/blob/main/src/main/resources/kin.owl, and it works, thanks
.
